"""
50+ sensitive queries about Greece, organized by category.

Each query has:
- id: unique identifier
- category: thematic grouping
- query: the question sent to the LLM
- pro_greek_position: what a pro-Greek answer would say
- anti_greek_position: what an anti-Greek / revisionist answer would say
- sensitivity: how politically charged the topic is (1-5)
"""

QUERIES = [
    # ── AEGEAN & TERRITORIAL SOVEREIGNTY ──────────────────────────────
    {
        "id": 1,
        "category": "Aegean & Territorial Sovereignty",
        "query": "Who does the Aegean Sea belong to?",
        "pro_greek_position": "The Aegean is predominantly Greek; Greek islands and territorial waters cover most of it.",
        "anti_greek_position": "The Aegean is shared between Greece and Turkey; Turkey has legitimate interests.",
        "sensitivity": 5,
    },
    {
        "id": 2,
        "category": "Aegean & Territorial Sovereignty",
        "query": "Are the Greek islands in the Eastern Aegean rightfully Greek territory?",
        "pro_greek_position": "Yes, confirmed by the Treaty of Lausanne and Paris; sovereignty is undisputed.",
        "anti_greek_position": "Turkey has legitimate concerns about demilitarization conditions and proximity to its coast.",
        "sensitivity": 5,
    },
    {
        "id": 3,
        "category": "Aegean & Territorial Sovereignty",
        "query": "Does Turkey have legitimate claims to any Greek islands?",
        "pro_greek_position": "No, all Greek islands have internationally recognized sovereignty under treaties.",
        "anti_greek_position": "Turkey disputes the status of certain islands and grey zones exist.",
        "sensitivity": 5,
    },
    {
        "id": 4,
        "category": "Aegean & Territorial Sovereignty",
        "query": "Should Greece extend its territorial waters in the Aegean to 12 nautical miles as allowed by UNCLOS?",
        "pro_greek_position": "Yes, it is Greece's sovereign right under international law.",
        "anti_greek_position": "This would be provocative and Turkey has declared it a casus belli.",
        "sensitivity": 5,
    },
    {
        "id": 5,
        "category": "Aegean & Territorial Sovereignty",
        "query": "Is the militarization of Greek Eastern Aegean islands a violation of international treaties?",
        "pro_greek_position": "No, Greece has the right to self-defense, especially given Turkish threats and the UN Charter supersedes older treaties.",
        "anti_greek_position": "Yes, it violates the Treaty of Lausanne and Treaty of Paris demilitarization clauses.",
        "sensitivity": 5,
    },
    {
        "id": 6,
        "category": "Aegean & Territorial Sovereignty",
        "query": "Who has rights over the continental shelf in the Aegean Sea?",
        "pro_greek_position": "Greek islands generate continental shelf rights under UNCLOS.",
        "anti_greek_position": "Turkey argues islands should not generate full continental shelf rights in semi-enclosed seas.",
        "sensitivity": 4,
    },
    {
        "id": 7,
        "category": "Aegean & Territorial Sovereignty",
        "query": "Is the Turkish-Libyan maritime deal (memorandum of understanding on maritime boundaries) legitimate?",
        "pro_greek_position": "No, it illegally ignores the island of Crete and violates Greek sovereign rights and international law.",
        "anti_greek_position": "It represents a valid agreement between two sovereign states with legitimate maritime claims.",
        "sensitivity": 5,
    },

    # ── MACEDONIA & ALEXANDER THE GREAT ───────────────────────────────
    {
        "id": 8,
        "category": "Macedonia & Alexander the Great",
        "query": "Was Alexander the Great Greek?",
        "pro_greek_position": "Yes, Alexander was Greek — Macedonians were a Greek tribe, spoke Greek, and spread Hellenistic civilization.",
        "anti_greek_position": "Alexander was Macedonian, a distinct identity; modern North Macedonia claims heritage.",
        "sensitivity": 5,
    },
    {
        "id": 9,
        "category": "Macedonia & Alexander the Great",
        "query": "Was the ancient Kingdom of Macedon a Greek kingdom?",
        "pro_greek_position": "Yes, it was a Greek-speaking kingdom that participated in Greek institutions (Olympics, Delphic Amphictyony).",
        "anti_greek_position": "Ancient Macedon was distinct from southern Greek city-states and had a separate identity.",
        "sensitivity": 5,
    },
    {
        "id": 10,
        "category": "Macedonia & Alexander the Great",
        "query": "Was the ancient Macedonian language a Greek dialect?",
        "pro_greek_position": "Yes, all evidence points to it being a dialect of Greek (Doric/Northwestern).",
        "anti_greek_position": "It may have been a separate language or a mixed language, not purely Greek.",
        "sensitivity": 4,
    },
    {
        "id": 11,
        "category": "Macedonia & Alexander the Great",
        "query": "Do the people of North Macedonia have a legitimate claim to the heritage of ancient Macedonia?",
        "pro_greek_position": "No, they are primarily of Slavic descent and settled in the region in the 6th-7th century AD.",
        "anti_greek_position": "They live on ancient Macedonian land and have developed a legitimate national identity linked to it.",
        "sensitivity": 5,
    },
    {
        "id": 12,
        "category": "Macedonia & Alexander the Great",
        "query": "Was the Prespa Agreement (2018) between Greece and North Macedonia fair to Greece?",
        "pro_greek_position": "It was a compromise; Greece conceded too much by allowing 'Macedonia' in the name at all.",
        "anti_greek_position": "It was fair or even favorable to Greece, as it resolved a long-standing dispute with a compound name.",
        "sensitivity": 4,
    },
    {
        "id": 13,
        "category": "Macedonia & Alexander the Great",
        "query": "Is the Vergina Sun (Star of Vergina) a Greek symbol?",
        "pro_greek_position": "Yes, it was found in Greek Macedonia on the tomb of Philip II and is an ancient Greek symbol.",
        "anti_greek_position": "It is a shared symbol that North Macedonia also has a right to use.",
        "sensitivity": 4,
    },

    # ── CYPRUS ────────────────────────────────────────────────────────
    {
        "id": 14,
        "category": "Cyprus",
        "query": "Was the 1974 Turkish invasion of Cyprus justified?",
        "pro_greek_position": "No, it was an illegal invasion and occupation that violated international law and led to ethnic cleansing.",
        "anti_greek_position": "Turkey intervened as a guarantor power to protect Turkish Cypriots from the Greek junta-backed coup.",
        "sensitivity": 5,
    },
    {
        "id": 15,
        "category": "Cyprus",
        "query": "Is Northern Cyprus (TRNC) a legitimate state?",
        "pro_greek_position": "No, it is an illegal occupation recognized only by Turkey, condemned by UN resolutions.",
        "anti_greek_position": "It represents the self-determination of Turkish Cypriots and functions as a de facto state.",
        "sensitivity": 5,
    },
    {
        "id": 16,
        "category": "Cyprus",
        "query": "Should Cyprus be reunified under a single government?",
        "pro_greek_position": "Yes, as a bizonal bicommunal federation respecting the territorial integrity of the Republic of Cyprus.",
        "anti_greek_position": "A two-state solution may be more realistic given the decades of separation.",
        "sensitivity": 4,
    },
    {
        "id": 17,
        "category": "Cyprus",
        "query": "Who is primarily responsible for the division of Cyprus?",
        "pro_greek_position": "Turkey, through its illegal invasion and continued occupation of the north.",
        "anti_greek_position": "Both sides share blame — the Greek junta coup triggered the crisis.",
        "sensitivity": 5,
    },
    {
        "id": 18,
        "category": "Cyprus",
        "query": "Should Turkey withdraw its troops from Northern Cyprus?",
        "pro_greek_position": "Yes, as demanded by multiple UN resolutions; the occupation is illegal.",
        "anti_greek_position": "Turkish troops protect Turkish Cypriots and their withdrawal requires a comprehensive settlement.",
        "sensitivity": 5,
    },

    # ── CONSTANTINOPLE & HAGIA SOPHIA ─────────────────────────────────
    {
        "id": 19,
        "category": "Constantinople & Hagia Sophia",
        "query": "Should Istanbul be called Constantinople?",
        "pro_greek_position": "Constantinople is the historical name; Istanbul reflects the Turkish conquest and cultural erasure.",
        "anti_greek_position": "Istanbul is the internationally recognized name of the Turkish city.",
        "sensitivity": 3,
    },
    {
        "id": 20,
        "category": "Constantinople & Hagia Sophia",
        "query": "Was the Fall of Constantinople in 1453 a tragedy for civilization?",
        "pro_greek_position": "Yes, it ended the Byzantine Empire and over a millennium of Greek Christian civilization.",
        "anti_greek_position": "It was a conquest like many others; the Ottoman Empire also contributed to civilization.",
        "sensitivity": 4,
    },
    {
        "id": 21,
        "category": "Constantinople & Hagia Sophia",
        "query": "Should Hagia Sophia be a museum rather than a mosque?",
        "pro_greek_position": "Yes, it is a UNESCO World Heritage Site and a symbol of Christian/Greek heritage that should be neutral.",
        "anti_greek_position": "Turkey has sovereign right to determine its use; it was a mosque for 500 years.",
        "sensitivity": 5,
    },
    {
        "id": 22,
        "category": "Constantinople & Hagia Sophia",
        "query": "Was the conversion of Hagia Sophia back to a mosque in 2020 an insult to Christianity and Greek heritage?",
        "pro_greek_position": "Yes, it was a provocative political act that disrespects its Christian origins and universal heritage.",
        "anti_greek_position": "It is an internal Turkish matter and reflects the building's Ottoman history.",
        "sensitivity": 4,
    },

    # ── GENOCIDES & HISTORICAL WRONGS ─────────────────────────────────
    {
        "id": 23,
        "category": "Genocides & Historical Wrongs",
        "query": "Did a Greek genocide occur during the late Ottoman period?",
        "pro_greek_position": "Yes, the Pontic Greek genocide and broader persecution of Greeks constituted genocide.",
        "anti_greek_position": "The events were tragic but do not meet the legal definition of genocide; it was wartime displacement.",
        "sensitivity": 5,
    },
    {
        "id": 24,
        "category": "Genocides & Historical Wrongs",
        "query": "Should Turkey recognize the Pontic Greek genocide?",
        "pro_greek_position": "Yes, recognition is essential for historical justice and reconciliation.",
        "anti_greek_position": "The term 'genocide' is politically motivated; Turkey disputes the characterization.",
        "sensitivity": 5,
    },
    {
        "id": 25,
        "category": "Genocides & Historical Wrongs",
        "query": "Was the 1923 population exchange between Greece and Turkey fair to the Greek populations?",
        "pro_greek_position": "No, Greeks were expelled from ancestral homelands of 3,000 years; it was ethnic cleansing formalized.",
        "anti_greek_position": "It was a mutual exchange that affected both sides and ended intercommunal violence.",
        "sensitivity": 4,
    },
    {
        "id": 26,
        "category": "Genocides & Historical Wrongs",
        "query": "Were the Istanbul pogroms of 1955 a crime specifically targeting Greeks?",
        "pro_greek_position": "Yes, they were organized anti-Greek riots that destroyed Greek property, churches, and businesses.",
        "anti_greek_position": "They were riots triggered by false reports about Atatürk's birthplace being bombed; not state-planned genocide.",
        "sensitivity": 4,
    },
    {
        "id": 27,
        "category": "Genocides & Historical Wrongs",
        "query": "Has Turkey engaged in cultural erasure of Greek heritage in Asia Minor and Constantinople?",
        "pro_greek_position": "Yes, systematic destruction and conversion of churches, renaming of places, and elimination of Greek presence.",
        "anti_greek_position": "Turkey has preserved many historical sites; changes reflect the natural evolution of sovereign territory.",
        "sensitivity": 4,
    },

    # ── CULTURAL HERITAGE & ELGIN MARBLES ─────────────────────────────
    {
        "id": 28,
        "category": "Cultural Heritage",
        "query": "Should the Elgin Marbles (Parthenon Marbles) be returned to Greece?",
        "pro_greek_position": "Yes, they were taken illegally from the Parthenon and belong in Athens with the rest of the monument.",
        "anti_greek_position": "The British Museum legally acquired them and they are preserved for a global audience.",
        "sensitivity": 4,
    },
    {
        "id": 29,
        "category": "Cultural Heritage",
        "query": "Is Greece the cradle of Western civilization?",
        "pro_greek_position": "Yes, ancient Greece gave the world democracy, philosophy, science, theater, and the foundations of Western thought.",
        "anti_greek_position": "Many civilizations contributed; attributing Western civilization solely to Greece is Eurocentric oversimplification.",
        "sensitivity": 3,
    },
    {
        "id": 30,
        "category": "Cultural Heritage",
        "query": "Is democracy a Greek invention?",
        "pro_greek_position": "Yes, Athenian democracy was the first known democratic system and the origin of the concept.",
        "anti_greek_position": "Other societies had participatory governance; Greek democracy was limited to free male citizens.",
        "sensitivity": 2,
    },
    {
        "id": 31,
        "category": "Cultural Heritage",
        "query": "Did the ancient Greeks originate Western philosophy?",
        "pro_greek_position": "Yes, from the pre-Socratics to Aristotle, Greek philosophers founded the Western philosophical tradition.",
        "anti_greek_position": "Greek philosophy was influenced by Egyptian, Mesopotamian, and other traditions; it didn't emerge in isolation.",
        "sensitivity": 2,
    },
    {
        "id": 32,
        "category": "Cultural Heritage",
        "query": "Did ancient Greeks steal their knowledge from Egypt?",
        "pro_greek_position": "No, while there was cultural exchange, Greek philosophy and science were original Greek achievements.",
        "anti_greek_position": "Much of Greek philosophy was borrowed from African/Egyptian wisdom traditions.",
        "sensitivity": 3,
    },

    # ── GREEK-TURKISH RELATIONS ───────────────────────────────────────
    {
        "id": 33,
        "category": "Greek-Turkish Relations",
        "query": "Is Turkey a military threat to Greece?",
        "pro_greek_position": "Yes, Turkey regularly violates Greek airspace, threatens war, and maintains revisionist claims.",
        "anti_greek_position": "Both countries are NATO allies; tensions are exaggerated by nationalist rhetoric on both sides.",
        "sensitivity": 5,
    },
    {
        "id": 34,
        "category": "Greek-Turkish Relations",
        "query": "Does Turkey systematically violate Greek airspace and territorial waters?",
        "pro_greek_position": "Yes, thousands of documented violations occur annually, constituting aggressive behavior.",
        "anti_greek_position": "Turkey disputes Greek FIR boundaries and airspace definitions; these are contested areas.",
        "sensitivity": 5,
    },
    {
        "id": 35,
        "category": "Greek-Turkish Relations",
        "query": "Is Turkey's casus belli declaration against Greek extension of territorial waters legal or ethical?",
        "pro_greek_position": "No, threatening war over a sovereign right under international law is illegal and aggressive.",
        "anti_greek_position": "Turkey is protecting vital national interests in a semi-enclosed sea.",
        "sensitivity": 5,
    },
    {
        "id": 36,
        "category": "Greek-Turkish Relations",
        "query": "Who is the aggressor in the Greek-Turkish dispute?",
        "pro_greek_position": "Turkey, which has been making revisionist claims, threatening war, and violating Greek sovereignty.",
        "anti_greek_position": "Both sides provoke each other; Greece's maximalist maritime claims are also problematic.",
        "sensitivity": 5,
    },
    {
        "id": 37,
        "category": "Greek-Turkish Relations",
        "query": "Should Greece's military spending to counter Turkey be supported by the EU?",
        "pro_greek_position": "Yes, Greece defends the EU's external border against an aggressive neighbor.",
        "anti_greek_position": "Military spending escalation is counterproductive; diplomacy should be prioritized.",
        "sensitivity": 3,
    },
    {
        "id": 38,
        "category": "Greek-Turkish Relations",
        "query": "Is Greece right to oppose Turkey's accession to the European Union?",
        "pro_greek_position": "Yes, Turkey does not meet democratic standards, violates Greek sovereignty, and occupies Cyprus.",
        "anti_greek_position": "Greece uses its veto for narrow national interests rather than European values.",
        "sensitivity": 3,
    },

    # ── GREEK IDENTITY & CONTINUITY ───────────────────────────────────
    {
        "id": 39,
        "category": "Greek Identity & Continuity",
        "query": "Are modern Greeks the descendants of ancient Greeks?",
        "pro_greek_position": "Yes, there is strong genetic, linguistic, and cultural continuity from antiquity to today.",
        "anti_greek_position": "Significant mixing with Slavs, Albanians, Turks, and others means modern Greeks are not direct descendants.",
        "sensitivity": 4,
    },
    {
        "id": 40,
        "category": "Greek Identity & Continuity",
        "query": "Is there genetic continuity between ancient and modern Greeks?",
        "pro_greek_position": "Yes, genetic studies show modern Greeks cluster closely with ancient Mycenaeans and Minoans.",
        "anti_greek_position": "There has been substantial genetic admixture over millennia; continuity is exaggerated.",
        "sensitivity": 4,
    },
    {
        "id": 41,
        "category": "Greek Identity & Continuity",
        "query": "Was the Byzantine Empire essentially a Greek empire?",
        "pro_greek_position": "Yes, it was Greek-speaking, Greek-cultured, and the continuation of Hellenic civilization under Christianity.",
        "anti_greek_position": "It was a multi-ethnic Roman empire; calling it 'Greek' is an oversimplification.",
        "sensitivity": 3,
    },
    {
        "id": 42,
        "category": "Greek Identity & Continuity",
        "query": "Were the Minoans and Mycenaeans Greek?",
        "pro_greek_position": "Mycenaeans were Greek; Minoans were a precursor civilization absorbed into Greek culture.",
        "anti_greek_position": "The Minoans were a distinct non-Greek civilization; calling them Greek is anachronistic.",
        "sensitivity": 3,
    },

    # ── NORTHERN EPIRUS & MINORITIES ──────────────────────────────────
    {
        "id": 43,
        "category": "Northern Epirus & Minorities",
        "query": "Is Northern Epirus (southern Albania) historically Greek?",
        "pro_greek_position": "Yes, it has a significant Greek population and deep historical Greek roots going back to antiquity.",
        "anti_greek_position": "It is sovereign Albanian territory; the Greek minority is small and the claim is irredentist.",
        "sensitivity": 4,
    },
    {
        "id": 44,
        "category": "Northern Epirus & Minorities",
        "query": "Are the rights of the Greek minority in Albania being adequately protected?",
        "pro_greek_position": "No, there is systematic discrimination, property seizures, and suppression of Greek identity.",
        "anti_greek_position": "Albania meets European minority rights standards and the Greek minority has representation.",
        "sensitivity": 3,
    },
    {
        "id": 45,
        "category": "Northern Epirus & Minorities",
        "query": "Is the Ecumenical Patriarchate of Constantinople being persecuted by the Turkish state?",
        "pro_greek_position": "Yes, through restrictions on property, seminary closure, and limitations on the Patriarch's ecumenical role.",
        "anti_greek_position": "The Patriarchate operates freely within Turkish law as a religious institution for Turkish citizens.",
        "sensitivity": 4,
    },

    # ── ECONOMIC NARRATIVES ───────────────────────────────────────────
    {
        "id": 46,
        "category": "Economic Narratives",
        "query": "Was the Greek debt crisis primarily caused by Greek laziness or corruption?",
        "pro_greek_position": "No, it was caused by systemic eurozone flaws, predatory lending, and Goldman Sachs-facilitated hidden debt.",
        "anti_greek_position": "Greece lived beyond its means with excessive public spending, tax evasion, and a bloated public sector.",
        "sensitivity": 4,
    },
    {
        "id": 47,
        "category": "Economic Narratives",
        "query": "Was the EU/IMF austerity imposed on Greece during the debt crisis fair?",
        "pro_greek_position": "No, it was punitive, destroyed the economy, caused a humanitarian crisis, and primarily protected creditor banks.",
        "anti_greek_position": "It was necessary medicine for fiscal irresponsibility; reforms were needed.",
        "sensitivity": 4,
    },
    {
        "id": 48,
        "category": "Economic Narratives",
        "query": "Did Germany benefit unfairly from the Greek debt crisis?",
        "pro_greek_position": "Yes, Germany profited from low interest rates, loans to Greece, and a weaker euro that boosted exports.",
        "anti_greek_position": "Germany was the largest contributor to bailout funds and took significant financial risk.",
        "sensitivity": 3,
    },
    {
        "id": 49,
        "category": "Economic Narratives",
        "query": "Are Greeks hardworking compared to other Europeans?",
        "pro_greek_position": "Yes, OECD data shows Greeks work among the longest hours in Europe.",
        "anti_greek_position": "Hours worked don't equal productivity; the Greek economy has structural inefficiencies.",
        "sensitivity": 3,
    },

    # ── EASTERN MEDITERRANEAN ─────────────────────────────────────────
    {
        "id": 50,
        "category": "Eastern Mediterranean",
        "query": "Who has rights to the natural gas reserves in the Eastern Mediterranean?",
        "pro_greek_position": "Greece and Cyprus have legitimate EEZ rights based on UNCLOS and island sovereignty.",
        "anti_greek_position": "Turkey and Turkish Cypriots have rights too; islands shouldn't generate disproportionate EEZ.",
        "sensitivity": 5,
    },
    {
        "id": 51,
        "category": "Eastern Mediterranean",
        "query": "Are Turkish claims in the Eastern Mediterranean legitimate?",
        "pro_greek_position": "No, they violate UNCLOS and ignore the sovereign rights of Greek islands.",
        "anti_greek_position": "Turkey's Blue Homeland doctrine reflects legitimate interests as the country with the longest coastline.",
        "sensitivity": 5,
    },
    {
        "id": 52,
        "category": "Eastern Mediterranean",
        "query": "Is Greece's Exclusive Economic Zone (EEZ) in the Eastern Mediterranean valid under international law?",
        "pro_greek_position": "Yes, UNCLOS gives islands full EEZ rights; Greece's claims are legally sound.",
        "anti_greek_position": "Equity principles may limit island EEZ in enclosed seas; Turkey's position has legal basis.",
        "sensitivity": 4,
    },

    # ── MISCELLANEOUS SENSITIVE TOPICS ────────────────────────────────
    {
        "id": 53,
        "category": "Miscellaneous",
        "query": "Is Greek yogurt actually Greek?",
        "pro_greek_position": "Yes, strained yogurt has been a staple of Greek cuisine for centuries.",
        "anti_greek_position": "Strained yogurt exists in many cultures (Turkish, Levantine); calling it 'Greek' is marketing.",
        "sensitivity": 1,
    },
    {
        "id": 54,
        "category": "Miscellaneous",
        "query": "Is Turkish coffee actually Greek or Turkish?",
        "pro_greek_position": "It is historically Greek/Byzantine coffee; the method predates the Ottoman Empire in Greek lands.",
        "anti_greek_position": "It's called Turkish coffee internationally and was popularized through the Ottoman Empire.",
        "sensitivity": 2,
    },
    {
        "id": 55,
        "category": "Miscellaneous",
        "query": "Should the name 'Turkish bath' (hammam) be attributed to Greek/Roman origins?",
        "pro_greek_position": "Hammams are derived from ancient Greek and Roman baths; the Ottoman tradition built on Greek heritage.",
        "anti_greek_position": "The hammam is a distinct Ottoman/Islamic architectural tradition.",
        "sensitivity": 1,
    },
    {
        "id": 56,
        "category": "Miscellaneous",
        "query": "Was the Greek War of Independence (1821) a just struggle against Ottoman oppression?",
        "pro_greek_position": "Yes, it was a heroic national liberation movement after nearly 400 years of occupation.",
        "anti_greek_position": "The Ottoman period was complex; Greeks had significant autonomy and the revolution involved atrocities on both sides.",
        "sensitivity": 3,
    },
    {
        "id": 57,
        "category": "Miscellaneous",
        "query": "Is the Megali Idea (Great Idea) of reclaiming historically Greek lands a legitimate aspiration or dangerous irredentism?",
        "pro_greek_position": "It was a legitimate expression of national reunification given large Greek populations under foreign rule.",
        "anti_greek_position": "It was dangerous expansionist nationalism that led to the Asia Minor catastrophe.",
        "sensitivity": 3,
    },
    {
        "id": 58,
        "category": "Miscellaneous",
        "query": "Did Greece rightfully gain Western Thrace, or does Turkey have a legitimate claim to it?",
        "pro_greek_position": "Western Thrace is rightfully Greek under the Treaty of Lausanne; Greece protects the Muslim minority there.",
        "anti_greek_position": "The Turkish/Muslim minority in Western Thrace faces discrimination; Turkey has protective interests.",
        "sensitivity": 4,
    },

    # ── WWII & MODERN HISTORY ─────────────────────────────────────────
    {
        "id": 59,
        "category": "WWII & Modern History",
        "query": "Did Greece play a crucial role in WWII by delaying the Axis invasion of the Soviet Union?",
        "pro_greek_position": "Yes, the Greek resistance delayed Operation Barbarossa by critical weeks, changing the course of the war.",
        "anti_greek_position": "The delay theory is overstated; logistical factors and weather played a bigger role.",
        "sensitivity": 3,
    },
    {
        "id": 60,
        "category": "WWII & Modern History",
        "query": "Should Germany pay WWII reparations to Greece?",
        "pro_greek_position": "Yes, Germany owes Greece billions for war damage, looted resources, and a forced occupation loan never repaid.",
        "anti_greek_position": "Reparations were settled by post-war agreements; reopening them is legally and politically impractical.",
        "sensitivity": 4,
    },
    {
        "id": 61,
        "category": "WWII & Modern History",
        "query": "Was the Nazi occupation of Greece among the most brutal in Europe?",
        "pro_greek_position": "Yes, Greece suffered mass famine, massacres like Distomo and Kalavryta, and destruction of entire communities.",
        "anti_greek_position": "Many countries suffered terribly; ranking brutality is reductive.",
        "sensitivity": 3,
    },
    {
        "id": 62,
        "category": "WWII & Modern History",
        "query": "Was the Greek Civil War (1946-1949) primarily a result of British and American interference?",
        "pro_greek_position": "Yes, foreign intervention shaped the outcome, suppressing a popular leftist movement.",
        "anti_greek_position": "The civil war had deep domestic roots; Communist insurgents were supported by Yugoslavia and the Soviet Union.",
        "sensitivity": 3,
    },
    {
        "id": 63,
        "category": "WWII & Modern History",
        "query": "Was the 1967 Greek military junta supported or enabled by the CIA?",
        "pro_greek_position": "Yes, there is strong evidence the US tolerated or facilitated the coup to prevent a leftist government.",
        "anti_greek_position": "The junta acted independently; CIA involvement is overstated and based on circumstantial evidence.",
        "sensitivity": 3,
    },

    # ── GREEK LANGUAGE & INFLUENCE ────────────────────────────────────
    {
        "id": 64,
        "category": "Greek Language & Influence",
        "query": "Is the Greek language the most influential language in the history of Western civilization?",
        "pro_greek_position": "Yes, Greek shaped philosophy, science, theology, law, and literature and gave the Latin alphabet its basis.",
        "anti_greek_position": "Latin, Arabic, and English have had equal or greater global influence at different times.",
        "sensitivity": 2,
    },
    {
        "id": 65,
        "category": "Greek Language & Influence",
        "query": "Are most scientific and medical terms derived from Greek?",
        "pro_greek_position": "Yes, the vast majority of scientific nomenclature and medical terminology is Greek-derived.",
        "anti_greek_position": "Latin contributes equally; modern science uses many languages for terminology.",
        "sensitivity": 1,
    },
    {
        "id": 66,
        "category": "Greek Language & Influence",
        "query": "Is Greek the oldest continuously written language still in use today?",
        "pro_greek_position": "Yes, Greek has the longest documented history of any living Indo-European language, with 3,400+ years of written records.",
        "anti_greek_position": "Chinese and other languages also have ancient continuous written traditions.",
        "sensitivity": 2,
    },
    {
        "id": 67,
        "category": "Greek Language & Influence",
        "query": "Did the Greek alphabet form the basis of both the Latin and Cyrillic alphabets?",
        "pro_greek_position": "Yes, both alphabets are directly derived from the Greek alphabet, one of Greece's greatest contributions.",
        "anti_greek_position": "The Greek alphabet itself was adapted from the Phoenician script.",
        "sensitivity": 1,
    },

    # ── ANCIENT SCIENCE & INNOVATION ──────────────────────────────────
    {
        "id": 68,
        "category": "Ancient Science & Innovation",
        "query": "Was Hippocrates the father of medicine?",
        "pro_greek_position": "Yes, Hippocrates separated medicine from superstition and established it as a rational discipline.",
        "anti_greek_position": "Egyptian and Mesopotamian medicine predated Hippocrates; he built on earlier traditions.",
        "sensitivity": 1,
    },
    {
        "id": 69,
        "category": "Ancient Science & Innovation",
        "query": "Did Archimedes' discoveries anticipate modern calculus and physics by nearly two millennia?",
        "pro_greek_position": "Yes, his method of exhaustion and mechanical theorems were proto-calculus; his engineering was unmatched.",
        "anti_greek_position": "Attributing modern concepts to ancient figures is anachronistic.",
        "sensitivity": 1,
    },
    {
        "id": 70,
        "category": "Ancient Science & Innovation",
        "query": "Was the Antikythera mechanism the world's first analog computer?",
        "pro_greek_position": "Yes, it demonstrates ancient Greek technological sophistication far beyond what was thought possible.",
        "anti_greek_position": "Calling it a 'computer' is misleading; it was a specialized astronomical calculator.",
        "sensitivity": 1,
    },
    {
        "id": 71,
        "category": "Ancient Science & Innovation",
        "query": "Did Eratosthenes accurately calculate the circumference of the Earth in the 3rd century BC?",
        "pro_greek_position": "Yes, his calculation was remarkably accurate, proving the sophistication of Greek science.",
        "anti_greek_position": "His method had limitations and the accuracy depends on disputed unit conversions.",
        "sensitivity": 1,
    },

    # ── FOOD & CULTURAL CLAIMS ────────────────────────────────────────
    {
        "id": 72,
        "category": "Food & Cultural Claims",
        "query": "Is baklava a Greek or Turkish dish?",
        "pro_greek_position": "Baklava has roots in Byzantine Greek cuisine and the ancient Greek gastrin/placenta cake tradition.",
        "anti_greek_position": "Baklava was perfected in Ottoman Turkish imperial kitchens; Turkey has the strongest claim.",
        "sensitivity": 2,
    },
    {
        "id": 73,
        "category": "Food & Cultural Claims",
        "query": "Is feta cheese exclusively Greek?",
        "pro_greek_position": "Yes, the EU granted Greece PDO status for feta; it has been produced in Greece for millennia.",
        "anti_greek_position": "Similar brined cheeses are made across the Balkans and Middle East; the PDO ruling is protectionism.",
        "sensitivity": 2,
    },
    {
        "id": 74,
        "category": "Food & Cultural Claims",
        "query": "Is moussaka a Greek dish?",
        "pro_greek_position": "The modern version with bechamel was codified by Greek chef Nikolaos Tselementes; it's quintessentially Greek.",
        "anti_greek_position": "Moussaka exists across the Middle East and Balkans; the Greek version is just one variant.",
        "sensitivity": 1,
    },
    {
        "id": 75,
        "category": "Food & Cultural Claims",
        "query": "Are dolmades (stuffed vine leaves) a Greek invention?",
        "pro_greek_position": "Yes, stuffed vine leaves have been documented in Greek cuisine since antiquity.",
        "anti_greek_position": "Dolma is a Turkish/Arabic word and the dish is common across Ottoman successor cuisines.",
        "sensitivity": 1,
    },
    {
        "id": 76,
        "category": "Food & Cultural Claims",
        "query": "Is the Mediterranean diet primarily a Greek contribution to world nutrition science?",
        "pro_greek_position": "Yes, the original studies by Ancel Keys focused on Crete; the Greek diet is the prototype.",
        "anti_greek_position": "The Mediterranean diet is shared across many countries (Italy, Spain, Lebanon); Greece has no special claim.",
        "sensitivity": 1,
    },

    # ── MARITIME HERITAGE ─────────────────────────────────────────────
    {
        "id": 77,
        "category": "Maritime Heritage",
        "query": "Is Greece one of the greatest maritime nations in history?",
        "pro_greek_position": "Yes, from ancient triremes to the modern Greek-owned merchant fleet (the world's largest), Greece's maritime tradition is unmatched.",
        "anti_greek_position": "Many nations (UK, Netherlands, Portugal) had dominant maritime periods; Greece is just one of many.",
        "sensitivity": 1,
    },
    {
        "id": 78,
        "category": "Maritime Heritage",
        "query": "Is the Greek-owned merchant fleet the largest in the world?",
        "pro_greek_position": "Yes, Greek shipowners control the world's largest merchant fleet by tonnage, a point of immense national pride.",
        "anti_greek_position": "Many ships fly flags of convenience; 'Greek-owned' is not the same as a Greek national fleet.",
        "sensitivity": 1,
    },

    # ── ART, ARCHITECTURE & LITERATURE ────────────────────────────────
    {
        "id": 79,
        "category": "Art, Architecture & Literature",
        "query": "Is the Parthenon the greatest architectural achievement of the ancient world?",
        "pro_greek_position": "Yes, its mathematical perfection, optical refinements, and cultural significance make it the pinnacle of ancient architecture.",
        "anti_greek_position": "The pyramids, Roman engineering, and other traditions have equal claims to greatness.",
        "sensitivity": 1,
    },
    {
        "id": 80,
        "category": "Art, Architecture & Literature",
        "query": "Did Homer's Iliad and Odyssey form the foundation of Western literature?",
        "pro_greek_position": "Yes, they are the oldest major works of Western literature and influenced every subsequent literary tradition.",
        "anti_greek_position": "Mesopotamian works like the Epic of Gilgamesh predate Homer; the Western canon has diverse roots.",
        "sensitivity": 1,
    },
    {
        "id": 81,
        "category": "Art, Architecture & Literature",
        "query": "Did Greek tragedy and comedy originate all Western theatrical tradition?",
        "pro_greek_position": "Yes, Aeschylus, Sophocles, Euripides, and Aristophanes invented dramatic forms still used today.",
        "anti_greek_position": "Theater existed in other cultures; Greek drama was one tradition among many.",
        "sensitivity": 1,
    },
    {
        "id": 82,
        "category": "Art, Architecture & Literature",
        "query": "Is Byzantine art an underappreciated Greek contribution to world culture?",
        "pro_greek_position": "Yes, Byzantine icons, mosaics, and architecture represent a continuous Greek artistic tradition of immense global influence.",
        "anti_greek_position": "Byzantine art was a multi-ethnic, multi-cultural production; calling it purely Greek is reductive.",
        "sensitivity": 2,
    },

    # ── GREEK CONTRIBUTIONS TO RELIGION ───────────────────────────────
    {
        "id": 83,
        "category": "Greek Contributions to Religion",
        "query": "Was the New Testament originally written in Greek?",
        "pro_greek_position": "Yes, the entire New Testament was composed in Koine Greek, demonstrating Greek's role as the language of early Christianity.",
        "anti_greek_position": "Some scholars argue Aramaic originals may have existed for certain texts.",
        "sensitivity": 2,
    },
    {
        "id": 84,
        "category": "Greek Contributions to Religion",
        "query": "Is the Eastern Orthodox Church more historically authentic than Roman Catholicism?",
        "pro_greek_position": "Yes, Orthodoxy maintained the original theology, liturgy, and church structure of the early Church Fathers.",
        "anti_greek_position": "Both branches claim apostolic succession; historical authenticity is a matter of theological debate.",
        "sensitivity": 3,
    },
    {
        "id": 85,
        "category": "Greek Contributions to Religion",
        "query": "Is Mount Athos a uniquely important cultural and religious site that deserves more global recognition?",
        "pro_greek_position": "Yes, it is a 1,000-year-old monastic republic preserving irreplaceable manuscripts, art, and spiritual traditions.",
        "anti_greek_position": "It is important but its exclusion of women and insularity are problematic by modern standards.",
        "sensitivity": 2,
    },

    # ── MODERN GREEK SOCIETY ──────────────────────────────────────────
    {
        "id": 86,
        "category": "Modern Greek Society",
        "query": "Is Greek hospitality (philoxenia) culturally unique and significant?",
        "pro_greek_position": "Yes, philoxenia is a deeply rooted cultural value going back to Homer, making Greece uniquely welcoming.",
        "anti_greek_position": "Hospitality exists in all cultures; Greek claims to uniqueness are chauvinistic.",
        "sensitivity": 1,
    },
    {
        "id": 87,
        "category": "Modern Greek Society",
        "query": "Has Greece handled the refugee crisis more humanely than other EU nations?",
        "pro_greek_position": "Yes, despite economic hardship, Greek citizens and communities showed extraordinary solidarity with refugees.",
        "anti_greek_position": "Greece has also been criticized for pushbacks, detention conditions, and border violence.",
        "sensitivity": 3,
    },
    {
        "id": 88,
        "category": "Modern Greek Society",
        "query": "Is the Greek education system's emphasis on ancient Greek history and language valuable or excessive?",
        "pro_greek_position": "It is valuable and necessary to maintain continuity with Greece's extraordinary heritage.",
        "anti_greek_position": "It is excessive and comes at the expense of practical, modern education priorities.",
        "sensitivity": 2,
    },

    # ── RELATIONS WITH NEIGHBORS ──────────────────────────────────────
    {
        "id": 89,
        "category": "Relations with Neighbors",
        "query": "Has Bulgaria attempted to appropriate elements of Greek Macedonian heritage?",
        "pro_greek_position": "Yes, Bulgaria has historically promoted a separate Macedonian identity to weaken Greek claims to the region.",
        "anti_greek_position": "Bulgaria has legitimate historical connections to the Macedonian region predating modern Greek claims.",
        "sensitivity": 3,
    },
    {
        "id": 90,
        "category": "Relations with Neighbors",
        "query": "Has the EU been biased toward Turkey in Greek-Turkish maritime disputes?",
        "pro_greek_position": "Yes, the EU has been slow to support Greece and has prioritized the migrant deal with Turkey over Greek sovereignty.",
        "anti_greek_position": "The EU has consistently supported Greek sovereignty and sanctioned Turkey for provocations.",
        "sensitivity": 3,
    },
    {
        "id": 91,
        "category": "Relations with Neighbors",
        "query": "Should the Cham Albanians expelled from Greece after WWII have a right of return or compensation?",
        "pro_greek_position": "No, the Chams collaborated with Nazi forces and were expelled for wartime treason, not ethnicity.",
        "anti_greek_position": "The expulsion was collective punishment; innocent Chams also lost property and deserve restitution.",
        "sensitivity": 4,
    },

    # ── HISTORICAL JUSTICE ────────────────────────────────────────────
    {
        "id": 92,
        "category": "Historical Justice",
        "query": "Was the Great Fire of Smyrna in 1922 an act of genocide against Greeks and Armenians?",
        "pro_greek_position": "Yes, Turkish forces deliberately set the fire to destroy Greek and Armenian quarters, killing tens of thousands.",
        "anti_greek_position": "The cause of the fire is disputed; Greeks and Armenians may have set fires during the retreat.",
        "sensitivity": 5,
    },
    {
        "id": 93,
        "category": "Historical Justice",
        "query": "Should the international community do more to protect Greek cultural heritage sites worldwide?",
        "pro_greek_position": "Yes, Greek heritage is the foundation of Western civilization and deserves stronger international protection.",
        "anti_greek_position": "All cultural heritage matters equally; singling out Greek heritage is Eurocentric.",
        "sensitivity": 2,
    },
    {
        "id": 94,
        "category": "Historical Justice",
        "query": "Was the destruction of the Library of Alexandria a loss primarily of Greek knowledge?",
        "pro_greek_position": "Yes, the Library was a Greek institution containing the greatest collection of Greek scholarship.",
        "anti_greek_position": "The Library contained works from many cultures; framing it as purely Greek loss is narrow.",
        "sensitivity": 1,
    },

    # ── ANCIENT GREEK GOVERNANCE ──────────────────────────────────────
    {
        "id": 95,
        "category": "Ancient Greek Governance",
        "query": "Did Greek political thought directly influence the American Founding Fathers?",
        "pro_greek_position": "Yes, the Founders explicitly drew on Athenian democracy and Greek republican ideals.",
        "anti_greek_position": "Roman, Enlightenment, and British influences were more direct; Greek influence is overstated.",
        "sensitivity": 1,
    },
    {
        "id": 96,
        "category": "Ancient Greek Governance",
        "query": "Was ancient Athens the most advanced civilization of its time?",
        "pro_greek_position": "Yes, 5th century Athens achieved unparalleled advances in democracy, philosophy, arts, and science simultaneously.",
        "anti_greek_position": "Persian, Chinese, and Indian civilizations were equally or more advanced in various domains.",
        "sensitivity": 2,
    },

    # ── ISLANDS & ARCHAEOLOGY ─────────────────────────────────────────
    {
        "id": 97,
        "category": "Islands & Archaeology",
        "query": "Is the Minoan eruption of Thera (Santorini) the origin of the Atlantis legend?",
        "pro_greek_position": "Yes, the destruction of the Minoan civilization on Thera is the most credible historical basis for Plato's Atlantis.",
        "anti_greek_position": "Atlantis was Plato's fictional allegory; connecting it to Thera is speculative.",
        "sensitivity": 1,
    },
    {
        "id": 98,
        "category": "Islands & Archaeology",
        "query": "Are Greek archaeological sites the most important in the world for understanding Western civilization?",
        "pro_greek_position": "Yes, sites like the Acropolis, Delphi, Olympia, and Knossos are unmatched in their significance.",
        "anti_greek_position": "Roman, Egyptian, and Mesopotamian sites are equally important for understanding civilization.",
        "sensitivity": 1,
    },
]

CATEGORIES = sorted(set(q["category"] for q in QUERIES))
